config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :pins
  get 'welcome/index'
  root 'welcome#index'

  get 'mypins' => 'pins#mypins'
  get 'pinsof/:user_id' => 'pins#pinsof', :as => "pinsof"

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pin.rb
class Pin < ApplicationRecord
	validates :photo, presence:true
	validates :description, presence:true

	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :pins
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!, except:[ :index, :show]

  
  def mypins
    @pins = current_user.pins
  end

  def pinsof
    @user_id = params[:user_id]
    @user = User.find(@user_id)
    @pins = @user.pins
  end

  # GET /pins
  # GET /pins.json

  def index
    @pins = Pin.all
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pins = current_user.pins
  end

  # GET /pins/new
  def new
    @pin = Pin.new
    @pins = current_user.pins
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins
  # POST /pins.json
  def create
    @pin = Pin.new(pin_params)
    @pin.user_id = current_user.id

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1
  # PATCH/PUT /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    @pin.destroy
    respond_to do |format|
      format.html { redirect_to pins_url, notice: 'Pin was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pin_params
      params.require(:pin).permit(:photo, :description, :name)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> Mi Pinterest</title>

     <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= stylesheet_link_tag    '/assets/application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag '/assets/application', 'data-turbolinks-track': 'reload' %>
	

	<!-- Latest compiled and minified JavaScript -->
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/masonry/4.2.0/masonry.pkgd.min.js">
    
  </script>

  </head>

  <body>
	<%= render 'shared/navbar' %>
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pins/_form.html.erb
<%= form_for(pin) do |f| %>
  <% if pin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

      <ul>
      <% pin.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <div class="field">
      <%= f.label :name, "Nombre" %>
      <%= f.text_field :name, :class => 'form-control', :placeholder => "Nombe del pin" %>
    </div>
  </div>

  <div class="form-group">
    <div class="field">
      <%= f.label :photo, "Foto" %>
      <%= f.text_field :photo, :class => 'form-control' , :placeholder => "Url de la foto" %>
    </div>
  </div>


  <div class="form-group">
    <div class="field">
      <%= f.label :description,  "Descripción" %>
      <%= f.text_area :description, :class => 'form-control', :rows => "10", :cols => "30" %>
    </div>
  </div>


  <div class="form-group">
    <div class="actions">
      <%= f.submit "Crear Pin", :class => "btn btn-primary" %>
    </div>
  </div>
<% end %>

app/views/pins/edit.html.erb
<div class="container">

<div class="row">
	<div class="col-md-6">
		<h1>Editing Pin</h1>
		<%= render 'form', pin: @pin %>
	</div>
</div>

		<%= link_to 'Show', @pin %> |
		<%= link_to 'Back', pins_path %>
</div>

app/views/pins/index.html.erb
<p id="notice"><%= notice %></p>
<p id="notice"><%= notice %></p>
<h1>Pins</h1>


<div class="grid" data-masonry= '{"ItemSelector": ".grid-item", "columnWidth": 190}' >
    <% @pins.each do |pin| %>
    
      <div class="grid-item" style="width: 20%">
      <div class="thumbnail">
         
        <%= image_tag(pin.photo, :class => 'img_responsive') %>
        <%= pin.name %>
         <%= pin.description %>
        <div class="buttons" style="margin-top: 10px; margin-bottom: 10px">
        <%= link_to 'Show', pin, :class => 'btn' %>
        <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
      </div>
    </div>
  </div>    
    <% end %>
<br>
</div>

<%= link_to 'New Pin', new_pin_path %>
</div>
<script type="text/javascript">
  $(' .grid').masonry({
    ItemSelector: '.grid-item', 
    columnWidth: 200
  });
  $(window).load(function(){
    $(' .grid').masonry({
      ItemSelector: '.grid-item', 
      columnWidth: 200
    });
  })

</script>>

app/views/pins/mypins.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Mis Pins</h1>

    <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
         <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img_responsive') %>
         <%= pin.description %>
        <div class="buttons" style="margin-top: 10px; margin-bottom: 10px">
        <%= link_to 'Show', pin, :class => 'btn' %>
        <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
        <% if user_signed_in? %>
        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        <% end %>
      </div>
      </div>
      </div>
    <% end %>


<br>
<% if user_signed_in? %>

<%= link_to 'New Pin', new_pin_path %>
<% end %>


<script type="text/javascript">
 var elem = document.querySelector('.grid');
var msnry = new Masonry( elem, {
  // options
  itemSelector: '.grid-item',
  columnWidth: 200
});
$(window).load(function(){
  var elem = document.querySelector('.grid');
var msnry = new Masonry( elem, {
  // options
  itemSelector: '.grid-item',
  columnWidth: 200
});

$('.grid').masonry({
  // options
  itemSelector: '.grid-item',
  columnWidth: 200
});
</script>
</div>

app/views/pins/new.html.erb
<div class="container">
	<h1>Agregar nuevo Pin</h1>

	<div class="row">
		<div class="col-md-6">
			<%= render 'form', pin: @pin, pins: @pins %>
		</div>
		</div>
		<p><%= link_to 'Back', pins_path %></p>

</div>

app/views/pins/pinsof.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<h1>Mis Pins</h1>

    <% @pins.each do |pin| %>
    <div class="col-md-3">
      <div class="thumbnail">
         <%= pin.name %>
        <%= image_tag(pin.photo, :class => 'img_responsive') %>
         <%= pin.description %>
        <div class="buttons" style="margin-top: 10px; margin-bottom: 10px">
        <%= link_to 'Show', (pin), :class => 'btn' %>
        <%= link_to 'Edit', edit_pin_path(pin), :class => 'btn' %>
        <% if user_signed_in? %>
        <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure?' }, :class => 'btn' %>
        <% end %>
      </div>
      </div>
      </div>
    <% end %>


<br>
<% if user_signed_in? %>

<%= link_to 'New Pin', new_pin_path %>
<% end %>

</div>

app/views/pins/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @pin.name %>
</p>



<p>
  <strong>Photo:</strong>
  <%= image_tag(@pin.photo, :style => 'width:500px') %>
</p>

<p>
  <strong>Description:</strong>
  <%= @pin.description %>
</p>



<%= link_to 'Edit', edit_pin_path(@pin) %> |
<%= link_to 'Back', pins_path %>


<%=	link_to "Mas pins del mismo usuario", pinsof_path(@pin.user.id) %>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-inverse" >
	  <div class="container-fluid">
	    <!-- Brand and toggle get grouped for better mobile display -->
	    <div class="navbar-header">
	      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
	        <span class="sr-only">Toggle navigation</span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	        <span class="icon-bar"></span>
	      </button>
	      <a class="navbar-brand" href="<%= root_path %>">Mi Pinterest</a>
	    </div>

	    <!-- Collect the nav links, forms, and other content for toggling -->
	    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
	      <ul class="nav navbar-nav">
	        <li><a href="">Nosotros <span class="sr-only">(current)</span></a></li>
	        <li><a href="<%= mypins_path %>">Mis Pins</a></li>
	        <li><a href="<%= pins_path %>">Pins</a></li>
	      </ul>
	      
	      <ul class="nav navbar-nav navbar-right">
	      <% if current_user.nil? %>
	        <li><a href="<%= new_user_session_path %>">Ingreso</a></li>
	        <li><a href="<%= new_user_registration_path %>">Registro</a></li>
	        <% else %>
	        <li><a href="<%= destroy_user_session_path %>" data-method="delete">Salir</a></li>
	        <% end %>
	      </ul>
	    </div><!-- /.navbar-collapse -->
	  </div><!-- /.container-fluid -->
	</nav>

app/views/welcome/index.html.erb
<div class="jumbotron">
<div class="container">
<h1 >Titulo</h1>
<a href="http://youtube.com" class="btn btn-primary"><span class="glyphicon glyphicon-fire" style=" color: orange"></span>Youtube </a>
</div>
</div>
<div class="container">
	<div class="row">
		<div class="col-md-4">
			<div class="page-header">
			  <h2 style="display: inline;">Example page header</h2>
			  <span class="label label-default">Default</span>
			</div>
	<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
	tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
	quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
	consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
	cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
	proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>
		<div class="col-md-4">
			<div class="page-header">
			  <h2>Example page header</h2>
			</div>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
		tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
		quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
		consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
		cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
		proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
		</div>
		<div class="col-md-4">
						<div class="page-header">
			  <h2>Example page header</h2>
			</div>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

						<h6>sub ... subtitulo</h6>
			<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
			tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
			quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
			consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
			cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
			proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
			<hr>
			<br>
			<a href="http://somosmovies.com">
			<img src="http://somosmovies.com/img/logo-sm.png" alt="logo de en 1 mes" class="img-responsive">
			</a>

			<ol>
				<li>Item 1</li>
				<li>item 2</li>
				<li>Item 3</li>
			</ol>

		</div>
	</div>

</div>